import logging
import uuid
import datetime
from typing import List

from src.db.neo4j_client import neo4j_client

logger = logging.getLogger(__name__)

def record_decision(
    customer_id: str,
    product_id: str,
    decision_outcome: str,
    rationale: str,
    evaluated_rule_ids: List[str]
) -> str:
    """
    Creates a new Decision node in Neo4j and explicitly links it to:
    1. The Customer who requested it [:MADE_FOR]
    2. The Product being evaluated [:EVALUATED_AGAINST]
    3. The specific Policy Clauses that formed the basis of the LLM's rationale [:BASED_ON]
    
    Args:
        customer_id (str): ID of the customer
        product_id (str): ID of the product
        decision_outcome (str): APPROVE, REJECT, or REFER
        rationale (str): The text explanation generated by the LLM
        evaluated_rule_ids (List[str]): IDs of the PolicyClauses used
        
    Returns:
        str: The ID of the newly created Decision node.
    """
    decision_id = f"DEC-{uuid.uuid4().hex[:12]}"
    timestamp = datetime.datetime.now().isoformat()
    
    logger.info(f"Recording trace for Decision '{decision_id}' (Outcome: {decision_outcome})")
    
    cypher_query = """
    // 1. Create the Decision Node
    CREATE (d:Decision {
        id: $decision_id,
        outcome: $outcome,
        rationale: $rationale,
        timestamp: $timestamp
    })
    
    // 2. Link to Customer
    WITH d
    MATCH (c:Customer {id: $customer_id})
    MERGE (d)-[:MADE_FOR]->(c)
    
    // 3. Link to Product (if applicable)
    WITH d
    MATCH (p:Product {id: $product_id})
    MERGE (d)-[:EVALUATED_AGAINST]->(p)
    
    // 4. Link to all evaluated Policy Clauses
    WITH d
    UNWIND $evaluated_rule_ids AS rule_id
    MATCH (pc:PolicyClause {id: rule_id})
    MERGE (d)-[:BASED_ON]->(pc)
    
    RETURN d.id AS decision_id
    """
    
    parameters = {
        "decision_id": decision_id,
        "outcome": decision_outcome,
        "rationale": rationale,
        "timestamp": timestamp,
        "customer_id": customer_id,
        "product_id": product_id,
        "evaluated_rule_ids": evaluated_rule_ids
    }
    
    try:
        results = neo4j_client.execute_query(cypher_query, parameters)
        if results:
            logger.info(f"Trace recorded successfully for {decision_id}.")
            return results[0]["decision_id"]
        else:
            logger.error("Decision node failed to return ID.")
            return ""
    except Exception as e:
        logger.error(f"Failed to record decision trace: {e}")
        raise
